server:
  port: 80

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 132692091688-i5u90uuq3fmhki96b7cjvcl8sb826t9i.apps.googleusercontent.com
            clientSecret: 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
          linkedin:
            clientId: ${LINKEDIN_CI}
            clientSecret: ${LINKEDIN_CS}
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: r_emailaddress, r_liteprofile
            clientName: Linkedin
          provider


#logging:
#  level:
#    org.springframework.security: TRACE